version: "3.8"

services:
  wiregock-app:
    build: .
    volumes:
      - mockfiles:${MOCKFILES_DIR}:ro
    environment:
      - MOCKFILES_DIR=${MOCKFILES_DIR:-/app/mockfiles}
      - PORT=${SERVER_PORT:-8080}
    ports:
      - "8080:8080"

  jsonKit:
    build: .
    volumes:
      - mockfiles:${MOCKFILES_DIR}:rw
    environment:
      - MOCKFILES_DIR=${MOCKFILES_DIR:-/app/mockfiles}
      - PORT=3000
      - WS_PORT=3030
    ports:
      - "3000:3000"
      - "3030:3030"

  ungit:
    build: .
    command: /app/start.sh
    volumes:
      - mockfiles:${MOCKFILES_DIR}:rw  # Ungit нужен доступ на запись
    environment:
      - UNGIT_PORT=8443
      - UNGIT_DIR=${MOCKFILES_DIR:-/app/mockfiles}
    ports:
      - "8443:8443"  # HTTPS-порт Ungit

volumes:
  mockfiles: